version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_ADDRESS=${DB_ADDRESS}
    ports:
      - "8081:8081"  
    depends_on:
      postgres:
        condition: service_healthy  
    volumes:
      - ./cmd:/app/cmd
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./cmd/migrate/migrations:/app/cmd/migrate/migrations

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:
    driver: local
