version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - PORT=${PORT}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_ADDRESS=${DB_ADDRESS}
      - GATEWAY_SERVICE_PORT=${GATEWAY_SERVICE_PORT}
    ports:
      - "8081:8081"  
    depends_on:
      postgres:
        condition: service_healthy  
    volumes:
      - ./cmd:/app/cmd
      - ./entrypoint.sh:/app/auth-service/entrypoint.sh  # Adjusted path
      - ./cmd/migrate/migrations:/app/auth-service/cmd/migrate/migrations  # Adjusted path
    networks:
      - it210-network  # Add this line to use the shared network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - it210-network  # Add this line to use the shared network

volumes:
  postgres_data:
    driver: local

networks:
  it210-network:  # Define the shared network
    external: true
